@echo off
call
gradle OKHttp3:assembleRelease Picasso:assembleRelease ProtoBuf:assembleRelease Plugin_Login:assembleRelease Plugin_Temp:assembleRelease Plugin_FileSelector:assembleRelease Host:assembleRelease
